name: Build Frontend (Win32 x64)

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout 仓库
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Setup Node.js (先 Node.js，再 pnpm)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      # 3️⃣ Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      # 4️⃣ 确认目录结构（可选调试）
      - name: List files
        run: dir

      # 5️⃣ Install dependencies
      - name: Install dependencies
        run: pnpm install
        working-directory: ./kas-frontend-app

      # 6️⃣ Build Electron App (Installer + Portable)
      - name: Build Electron App
        run: pnpm run electron:build -- --win nsis portable --x64
        working-directory: ./kas-frontend-app
        env:
          CI: true

      # 7️⃣ Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kas-frontend-win-x64
          path: ./kas-frontend-app/dist_electron/**

      # 8️⃣ Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: ./kas-frontend-app/dist_electron/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
